// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Saon.DataAccess;

namespace Saon.DataAccess.Migrations.TestContextMigrationMigrations
{
    [DbContext(typeof(TestContextMigration))]
    [Migration("20200526011700_ThirdMigration")]
    partial class ThirdMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Saon.Entities.Job", b =>
                {
                    b.Property<int>("IdJob")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("IdJob");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            IdJob = 1,
                            CreatedAt = new DateTime(2020, 5, 25, 19, 17, 0, 449, DateTimeKind.Local).AddTicks(7050),
                            Description = "Descripcion about .net developer",
                            ExpiredAt = new DateTime(2020, 6, 24, 19, 17, 0, 450, DateTimeKind.Local).AddTicks(7354),
                            JobTitle = ".NET Developer"
                        },
                        new
                        {
                            IdJob = 2,
                            CreatedAt = new DateTime(2020, 5, 25, 19, 17, 0, 450, DateTimeKind.Local).AddTicks(7828),
                            Description = "Descripcion about QA Analyst",
                            ExpiredAt = new DateTime(2020, 6, 24, 19, 17, 0, 450, DateTimeKind.Local).AddTicks(7841),
                            JobTitle = ".QA Analyst"
                        },
                        new
                        {
                            IdJob = 3,
                            CreatedAt = new DateTime(2020, 5, 25, 19, 17, 0, 450, DateTimeKind.Local).AddTicks(7855),
                            Description = "Descripcion about Solution Architec",
                            ExpiredAt = new DateTime(2020, 6, 24, 19, 17, 0, 450, DateTimeKind.Local).AddTicks(7856),
                            JobTitle = "Solution Architec"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
